language: python
python:
  - "3.8"
  - "3.9"
  # - "3.10" # Travis fails to install Python 3.10
  - "nightly"  # nightly build

before_install:
  - pip install --user codecov

after_success:
  - codecov --file coverage/lcov.info --disable search

install:
  - pip install -r requirements.txt

script:
  - pytest
